language: php
php:
  - '7.2'
  - '7.3'
  - nightly

matrix:
  allow_failures:
    - php: nightly

install:
  - composer install

script: ./vendor/bin/phpunit --configuration ./tests/phpunit.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
